### ISSUE TITLE
[EVENT] WorldLoadSuccess Loaded logged but the function does not fire

### ISSUE THREAD

**Issue by FranciZ** [breningham/nativescript-wikitude#2]
Hi,

I'm using Wikitude component in a modal and the first time the modal and the Wikitude component load the `(WorldLoadSuccess)="onWorldLoaded($event)"` does execute.

But the second time that modal opens the function does not execute even though the console does log `[EVENT] WorldLoadSuccess Loaded`.

The same problem persists in the demo-ng if I load the `Wikitude` component on a separate page and navigate away and back again. The console does log `[EVENT] WorldLoadSuccess Loaded` but the function does not fire.

Help appreciated.

Thank you!

**Comment by breningham** [comment]
Thanks for reporting this, i'll look into it.

**Comment by FranciZ** [comment]
@breningham Thanks! Quick question. Do you use this plugin in production? What are your experiences with the stability and performance?

**Comment by breningham** [comment]
We do, you can see it in action on the buzzin app (on both android and iOS) 

There are some caveats for the stability but we are always working to improve it. 

I managed to fix the issue on Android, do you also have similar problems on iOS?

**Comment by FranciZ** [comment]
Perfect, will check out on Android and let you know!

>There are some caveats for the stability but we are always working to improve it.

Any tips on what can cause issues that you've discovered.

Thanks for sharing the plugin and helping out!

**Comment by breningham** [comment]
Main thing is (for performance) make sure you actually set the features required for the specific ar scene... By default I just enable everything, but if you don't need instant tracking you can disable it. Saves on battery drainage too

**Comment by breningham** [comment]
Did the update work?

**Comment by FranciZ** [comment]
It did work. Thanks for taking care of it and sorry for the late response.
